fix: scripts
ostis-ai/ostis-web-platform pull request #104
Opened 2024-02-09 14:42 UTC by MakarenkoAI

remove items

2024-02-12 07:30 UTC, NikitaZotov requested changes

2024-02-12 07:30 UTC, NikitaZotov commented on scripts/build_sc_component_manager.sh
> -export ROOT_CMAKE_PATH="${SC_COMPONENT_MANAGER_PATH}"
This script will not build sc-component manager with these changes. It is needed to think about that we can build sc-machine and sc-component-manager separately, but without envs force changes

2024-02-12 21:43 UTC, NikitaZotov approved these changes

2024-02-13 06:06 UTC, MksmOrlov approved these changes

2024-02-13 06:53 UTC, merged