scripts: add build_platform script
ostis-ai/ostis-web-platform pull request #106
Opened 2024-02-21 13:10 UTC by MakarenkoAI

2024-02-21 19:17 UTC, MksmOrlov approved these changes

2024-02-22 08:01 UTC, NikitaZotov requested changes

2024-02-22 08:01 UTC, NikitaZotov commented on scripts/build_platform.sh
> +stage "Ostis-web-platform built successfully"
```suggestion
stage "OSTIS-web-platform built successfully"
```

2024-02-22 08:01 UTC, NikitaZotov commented on scripts/build_platform.sh
Update changelog

2024-02-23 11:04 UTC, NikitaZotov approved these changes

2024-02-23 11:38 UTC, merged