feat: improve build
ostis-ai/ostis-web-platform pull request #108
Opened 2024-03-05 16:04 UTC by NikitaZotov

Update changelog is not needed

2024-03-06 08:46 UTC, MksmOrlov requested changes

2024-03-06 08:46 UTC, MksmOrlov commented on scripts/build_platform.sh
> +stage "OSTIS-web-platform is built successfully"
```suggestion
stage "ostis-web-platform is built successfully"
```

2024-03-10 10:56 UTC, MakarenkoAI commented on scripts/build_platform.sh
> +stage "OSTIS-web-platform is built successfully"
why?

2024-03-10 10:56 UTC, MakarenkoAI approved these changes

2024-03-12 07:30 UTC, MksmOrlov commented on scripts/build_platform.sh
> +stage "OSTIS-web-platform is built successfully"
потому что there is no such identifier "OSTIS-web-platform", we have "OSTIS Platform" as standard entity and ostis-web-platform as a repository

2024-03-12 07:41 UTC, MksmOrlov requested changes

2024-03-12 07:41 UTC, MksmOrlov commented on README.md
4. sc-component-manager

2024-03-16 16:36 UTC, MksmOrlov approved these changes

2024-03-16 19:04 UTC, merged