Update build system
ostis-ai/ostis-web-platform pull request #119
Opened 2024-12-13 16:52 UTC by NikitaZotov

2024-12-26 14:55 UTC, KovalM approved these changes

2025-01-27 14:51 UTC, kilativ-dotcom requested changes

2025-01-27 14:51 UTC, kilativ-dotcom commented on docs/changelog.md
> +- All build and run scripts have been removed. This was done due to changes in the build system of the machine. So now this repository is most suitable for developers, not for consumers.
```suggestion
- All build and run scripts have been removed. This was done due to changes in the build system of the sc-machine. So now this repository is most suitable for developers, not for consumers.
```

2025-01-27 14:51 UTC, kilativ-dotcom commented on README.md
> +  # to build scp-machine, see https://ostis-ai.github.io/scp-machine/build/quick_start/#start-develop-sc-machine-with-conan
need to change text after last #

2025-01-27 14:51 UTC, kilativ-dotcom commented on README.md
> +  # to build sc-component-manager, see https://ostis-ai.github.io/sc-component-manager/build/quick_start/#start-develop-sc-machine-with-conan
need to change text after last #

2025-01-27 14:51 UTC, kilativ-dotcom commented on README.md
> +  python3 server/app.py
sc-web uses venv

2025-01-27 14:51 UTC, kilativ-dotcom commented on README.md
> +  conan export-pkg .
![image](https://github.com/user-attachments/assets/d1f10a91-a3b7-4eef-a162-271e59ecc165)
got this error

2025-02-03 07:35 UTC, kilativ-dotcom requested changes

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
line 42 fails
![image](https://github.com/user-attachments/assets/7ca8a19e-5595-4c16-b78a-3d865a3ca2fc)

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
> +  # after building projects there should be three folders `build/Debug` in sc-machine, scp-machine and sc-component-manager
sc-machine was built in release, there is only 'Release' folder in 'build'

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
> +  cd sc-web
sc-web is inside interface

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
> +  python3 server/app.py
this command is not for build

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
>    docker compose run machine build
there are several runs that don't mention --rm

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
> +  ./sc-machine/build/Debug/bin/sc-machine -s kb.bin \
sc-machine does not have Debug folder

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
> +  ./sc-machine/build/Debug/bin/sc-builder -i repo.path -o kb.bin --clear
error like in docker
![image](https://github.com/user-attachments/assets/9e0f5701-6e42-43de-a3aa-ec5ce09c015f)

2025-02-03 07:35 UTC, kilativ-dotcom commented on README.md
>  ## Usage
previous usage section had some intel on steps to launch interface

2025-02-03 07:40 UTC, kilativ-dotcom commented on README.md
ok, I changed branch in manager and it was fixed

2025-02-03 07:40 UTC, kilativ-dotcom commented on README.md
> +  ./sc-machine/build/Debug/bin/sc-builder -i repo.path -o kb.bin --clear
ok, I changed branch in manager and it was fixed

2025-02-03 12:42 UTC, kilativ-dotcom requested changes

2025-02-03 12:42 UTC, kilativ-dotcom commented on README.md
> +  # after building projects there should be three folders `build/Debug` in sc-machine, scp-machine and sc-component-manager
was something changed?

2025-02-03 12:42 UTC, kilativ-dotcom commented on README.md
>    docker compose run machine build
some are left

2025-02-03 12:42 UTC, kilativ-dotcom commented on README.md
> +    -e "sc-machine/build/Debug/lib/extensions;scp-machine/build/Debug/lib/extensions;sc-component-manager/build/Debug/lib/extensions"
no debug folder in sc-machine

2025-02-03 13:24 UTC, NikitaZotov commented
@ellipsis, review this PR, please

2025-02-03 13:41 UTC, NikitaZotov commented
@ellipsis, review this PR, please

2025-02-03 15:55 UTC, kilativ-dotcom approved these changes

2025-02-03 15:57 UTC, merged