Unify config for sc-server and sc-builder
ostis-ai/ostis-web-platform pull request #21
Opened 2022-07-21 00:00 UTC by NikitaZotov

2022-07-21 10:35 UTC, SHtress requested changes

2022-07-21 10:35 UTC, SHtress commented on README.md
> +<<<<<<< HEAD
Remove

2022-07-21 10:35 UTC, SHtress commented on latex/latexmkrc
> +$ENV{'TZ'}='Europe/Minsk';
Newline

2022-07-21 10:35 UTC, SHtress commented on scripts/install_texstudio.sh
> +sudo apt install texstudio
Users can use not only texstudio, script probably should download tex deps that you need to build document but you can use for this different tools like texmaker

2022-07-21 10:35 UTC, SHtress commented on docs/ostis_web_platform.tex
> +Популярность и развитость такого рода средств приводит к тому, что на первый взгляд целесообразным и эффективным кажется вариант реализации \textit{программного варианта реализации платформы интерпре
Better reformulate sentence "по которым было принято решение о реализации \textit{программного варианта реализации платформы интерпретации sc-моделей} с нуля".

2022-07-21 10:35 UTC, SHtress commented on docs/ostis_web_platform.tex
> +    По совокупности перечисленных причин было принято решение о реализации \textit{программного варианта реализации платформы интерпретации sc-моделей} "с нуля"{} с учетом особенностей хранения и обр
Again try not to say "с нуля" say something like our own solution/model/realization

2022-07-21 10:35 UTC, SHtress commented on docs/ostis_web_platform.tex
> +Данный вариант реализации распространяется под open-source лицензией, для хранения исходных текстов используется хостинг Github и коллективная учетная запись ostis-ai.
Be careful with license

2022-07-21 10:35 UTC, SHtress commented on scripts/run_texstudio.sh
> +texstudio ../latex/main.tex
Are you sure we need this?

2022-07-29 08:04 UTC, SHtress approved these changes

2022-07-29 14:57 UTC, KovalM approved these changes

2022-07-29 16:01 UTC, KovalM requested changes

2022-07-29 16:01 UTC, KovalM commented on scripts/run_scweb.sh
> +python3 app.py
I propose use run_scweb.sh from sc-web

2022-07-31 18:04 UTC, KovalM approved these changes

2022-08-01 11:54 UTC, SHtress approved these changes

2022-08-01 15:49 UTC, merged